services:
  postgres:
    image: postgres:16-alpine
    container_name: nabor_postgres
    environment:
      POSTGRES_USER: nabor
      POSTGRES_PASSWORD: nabor_secret
      POSTGRES_DB: nabor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: nabor_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: nabor
      MONGO_INITDB_ROOT_PASSWORD: nabor_secret
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:5
    container_name: nabor_neo4j
    environment:
      NEO4J_AUTH: neo4j/nabor_secret
    ports:
      - "7474:7474"  # UI web
      - "7687:7687"  # Bolt (connexion applicative)
    volumes:
      - neo4j_data:/data

  redis:
    image: redis:7-alpine
    container_name: nabor_redis
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit
    container_name: nabor_mailpit
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # UI web

volumes:
  postgres_data:
  mongo_data:
  neo4j_data:
